[package]
name = "strain"
version = "0.0.1"
edition = "2021"
description = "A CPU stressing utility written in Rust"
license = "MIT"

[dependencies]
rug = "1.24.1"

[profile.release]
strip = "symbols"
lto = true
